/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class FontService {
  constructor()
  loadFont(path: string): void
  getFontFamily(): string
  getFontStyle(): string
  getFontVersion(): number
  getUnitsPerEm(): number
  getAscender(): number
  getDescender(): number
  getCapHeight(): number
  getXHeight(): number
  getGlyphCount(): number
}
