/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsMetrics {
  unitsPerEm: number
  ascender: number
  descender: number
  capHeight: number
  xHeight: number
}
export declare class Contour {
  id: ContourId
  points: Array<Point>
  closed: boolean
}
export declare class ContourId { }
export declare class PointId { }
export declare class Glyph {
  name: string
  unicode: number
  contours: Record<ContourId, Contour>
  xAdvance: number
}
export declare class Point { }
export declare class FontEngine {
  constructor()
  loadFont(path: string): void
  getFontFamily(): string
  getFontStyle(): string
  getFontVersion(): number
  getMetrics(): JSMetrics
  getGlyphCount(): number
}
