[workspace]
resolver = "2"
members = ["crates/*"]


[workspace.dependencies]
shift-events = { path = "crates/shift-events" }
shift-font = { path = "crates/shift-font" }
shift-editor = { path = "crates/shift-editor" }
shift-unicode = { path = "crates/shift-unicode" }
