[workspace]
resolver = "2"
members = ["crates/*"]


[workspace.package]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
shift-wire = { path = "crates/shift-wire" }
shift-backends = { path = "crates/shift-backends" }
shift-bridge = { path = "crates/shift-bridge" }
shift-font = { path = "crates/shift-font" }
shift-slug = { path = "crates/shift-slug" }
shift-specimen = { path = "crates/shift-specimen" }
shift-store = { path = "crates/shift-store" }
shift-workspace = { path = "crates/shift-workspace" }

[profile.e2e]
inherits = "release"
opt-level = 1
codegen-units = 256
