/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsFontMetrics {
  unitsPerEm: number
  ascender: number
  descender: number
  capHeight: number
  xHeight: number
}
export interface JsFontMetaData {
  family: string
  styleName: string
  version: number
}
export const enum PointTypeJS {
  OnCurve = 0,
  OffCurve = 1
}
export declare class FontEngine {
  constructor()
  loadFont(path: string): void
  getMetadata(): JSFontMetaData
  getMetrics(): JSFontMetrics
  getGlyphCount(): number
  startEditSession(unicode: number): void
  endEditSession(): void
  addEmptyContour(): number
}
