export const DIRECTION_RING_OFFSET = 6;
export const DIRECTION_INNER_SIZE_OFFSET = 1;
export const LAST_HANDLE_LERP_SPACING = 0.25;
export const LAST_HANDLE_EDGE_OFFSET = 0.025;

export const START_TRIANGLE_GAP = 3;
