import type {
  ContourId,
  PointId,
  AnchorId,
  ComponentId,
  GuidelineId,
  GlyphId,
  LayerId,
  SourceId,
} from "../ids";

// This file is generated from crates/shift-bridge/index.d.ts.
// Run `pnpm generate:bridge-types` after rebuilding shift-bridge declarations.
// Do not edit this file manually.

export type GlyphName = string;
export type Unicode = number;

export interface BridgeApi {
  createUntitledWorkspace(storePath: string, options?: NewWorkspace | undefined | null): void
  closeWorkspace(): void
  saveWorkspace(): number
  saveWorkspaceAs(path: string): number
  exportWorkspace(request: FontExportRequest): Promise<FontExportResult>
  getMetadata(): FontMetadata
  getMetrics(): FontMetrics
  getGlyphCount(): number
  getGlyphs(): Array<GlyphRecord>
  updateGlyphIdentity(fromName: GlyphName, name: GlyphName, unicodes: Array<Unicode>): void
  /**
   * Applies one intent set as a single atomic workspace apply.
   *
   * Editing kinds decode through `map_intent` into `Font::apply_intents`;
   * `createGlyph` keeps its workspace-verb path until font-level verbs get
   * intent homes (CS4 tail). Sets must be homogeneous: font-level and
   * editing intents never share a tick.
   */
  apply(intents: Array<FontIntent>, label?: string | undefined | null): AppliedChange
  /**
   * Replays the most recent ledger entry's pre states; `null` when the
   * undo stack is empty.
   */
  undo(): AppliedChange | null
  /**
   * Replays the most recent undone entry's post states; `null` when the
   * redo stack is empty.
   */
  redo(): AppliedChange | null
  /**
   * Id-addressed glyph state: the stable-identity twin of
   * `get_glyph_state`. References survive renames; no name lookup.
   */
  getGlyph(glyphId: GlyphId, sourceId: SourceId): GlyphState | null
  getGlyphState(glyphHandle: GlyphHandle, sourceId: SourceId): GlyphState | null
  isVariable(): boolean
  getAxes(): Array<Axis>
  getSources(): Array<Source>
  getPersistedVersion(): number
  isDirty(): boolean
  createGlyph(name: GlyphName, unicodes: Array<Unicode>): GlyphId
  createGlyphLayer(glyphId: GlyphId, sourceId: SourceId): LayerId
  setXAdvance(layerId: LayerId, width: number): GlyphValueChange
  translateLayer(layerId: LayerId, dx: number, dy: number): GlyphValueChange
  addPoint(layerId: LayerId, contourId: ContourId, x: number, y: number, pointType: PointType, smooth: boolean): GlyphStructureChange
  insertPointBefore(layerId: LayerId, beforePointId: PointId, x: number, y: number, pointType: PointType, smooth: boolean): GlyphStructureChange
  addContour(layerId: LayerId): GlyphStructureChange
  openContour(layerId: LayerId, contourId: ContourId): GlyphStructureChange
  closeContour(layerId: LayerId, contourId: ContourId): GlyphStructureChange
  reverseContour(layerId: LayerId, contourId: ContourId): GlyphStructureChange
  applyBooleanOp(layerId: LayerId, contourIdA: ContourId, contourIdB: ContourId, operation: string): GlyphStructureChange
  removePoints(layerId: LayerId, pointIds: Array<PointId>): GlyphStructureChange
  toggleSmooth(layerId: LayerId, pointId: PointId): GlyphStructureChange
  /**
   * Bulk position sync. IDs are stable typed strings from the current glyph state.
   * Coords are interleaved [x0, y0, x1, y1, ...].
   */
  applyPositionPatch(layerId: LayerId, pointIds?: Array<PointId> | null, pointCoords?: Float64Array | undefined | null, anchorIds?: Array<AnchorId> | null, anchorCoords?: Float64Array | undefined | null): void
  restoreState(layerId: LayerId, structure: GlyphStructure, values: Float64Array): GlyphStructureChange
}

export interface GlyphHandle {
  name: GlyphName
  unicode?: Unicode
}

export interface FontExportRequest {
  path: string
  format: string
}

export interface FontExportResult {
  path: string
  format: string
}

export interface NewWorkspace {
  familyName?: string
  unitsPerEm?: number
}
export interface AddContourIntent {
  layerId: LayerId
  contourId: ContourId
  closed: boolean
}

export interface AddPointsIntent {
  layerId: LayerId
  /** Absent when `before` carries the anchor; Rust derives the contour. */
  contourId?: ContourId
  /** Insert before this point; append when absent. */
  before?: PointId
  points: Array<PointSeed>
}

export interface AnchorData {
  id: AnchorId
  name?: string
}

/** Pure-state response to `apply`: no change records cross to the renderer. */
export interface AppliedChange {
  layers: Array<LayerReplaced>
  /** Full records list when glyph identity changed; absent when untouched. */
  glyphs?: Array<GlyphRecord>
  /** Stable ids: references survive renames without re-indexing. */
  dependents: Array<GlyphId>
}

export interface Axis {
  tag: string
  name: string
  minimum: number
  default: number
  maximum: number
  hidden: boolean
}

export interface AxisTent {
  axisTag: string
  lower: number
  peak: number
  upper: number
}

export interface BooleanOpIntent {
  layerId: LayerId
  contourIdA: ContourId
  contourIdB: ContourId
  /** "union" | "subtract" | "intersect" | "difference" */
  operation: string
}

export interface ComponentData {
  id: ComponentId
  baseGlyphName: GlyphName
}

export interface ContourData {
  id: ContourId
  points: Array<PointData>
  closed: boolean
}

/**
 * CS0 walking-skeleton intent. A stringly union covering exactly the two
 * skeleton kinds; CS1 replaces this with per-variant intent structs.
 */
export interface FontIntent {
  /**
   * Discriminator naming the populated payload field. Editing kinds:
   * "addPoints" | "addContour" | "setContourClosed" | "movePoints" |
   * "setPointSmooth" | "removePoints" | "reverseContour" |
   * "translatePoints" | "setXAdvance" | "applyBooleanOp".
   * Skeleton leftover until font-level verbs land: "createGlyph".
   */
  kind: string
  addPoints?: AddPointsIntent
  addContour?: AddContourIntent
  setContourClosed?: SetContourClosedIntent
  movePoints?: MovePointsIntent
  setPointSmooth?: SetPointSmoothIntent
  removePoints?: RemovePointsIntent
  reverseContour?: ReverseContourIntent
  translatePoints?: TranslatePointsIntent
  setXAdvance?: SetXAdvanceIntent
  applyBooleanOp?: BooleanOpIntent
  name?: GlyphName
  unicodes?: Array<Unicode>
}

export interface FontMetadata {
  familyName?: string
  styleName?: string
  versionMajor?: number
  versionMinor?: number
  copyright?: string
  trademark?: string
  designer?: string
  designerUrl?: string
  manufacturer?: string
  manufacturerUrl?: string
  license?: string
  licenseUrl?: string
  description?: string
  note?: string
}

export interface FontMetrics {
  unitsPerEm: number
  ascender: number
  descender: number
  capHeight?: number
  xHeight?: number
  lineGap?: number
  italicAngle?: number
  underlinePosition?: number
  underlineThickness?: number
}

export interface GlyphChangedEntities {
  pointIds: Array<PointId>
  contourIds: Array<ContourId>
  anchorIds: Array<AnchorId>
  guidelineIds: Array<GuidelineId>
  componentIds: Array<ComponentId>
}

export interface GlyphMaster {
  sourceId: SourceId
  sourceName: string
  isDefaultSource: boolean
  location: Location
  structure: GlyphStructure
  values: Float64Array
}

export interface GlyphRecord {
  id: GlyphId
  name: GlyphName
  unicodes: Array<Unicode>
  componentBaseGlyphNames: Array<GlyphName>
}

export interface GlyphState {
  layerId: LayerId
  structure: GlyphStructure
  /** Numeric glyph state ordered to match `GlyphStructure`. */
  values: Float64Array
  variationData?: GlyphVariationData
}

export interface GlyphStructure {
  contours: Array<ContourData>
  anchors: Array<AnchorData>
  components: Array<ComponentData>
}

export interface GlyphStructureChange {
  structure: GlyphStructure
  values: Float64Array
  changed: GlyphChangedEntities
}

export interface GlyphValueChange {
  values: Float64Array
  changed: GlyphChangedEntities
}

export interface GlyphVariationData {
  /** One entry per region. Inner = tents on the axes the region depends on. */
  regions: Array<Array<AxisTent>>
  /** Deltas are flattened in `GlyphState::values` order. */
  deltas: Array<Float64Array>
}

/**
 * Replace-grade state for one touched layer; the renderer folds by
 * substitution, never by interpreting changes.
 */
export interface LayerReplaced {
  layerId: LayerId
  /** Present only when the layer's structure changed. */
  structure?: GlyphStructure
  values: Float64Array
  changed: GlyphChangedEntities
}

export interface Location {
  values: Record<string, number>
}

export interface MovePointsIntent {
  layerId: LayerId
  pointIds: Array<PointId>
  /** Interleaved absolute coordinates: x0, y0, x1, y1, … */
  coords: Array<number>
}

export interface PointData {
  id: PointId
  pointType: PointType
  smooth: boolean
}

/**
 * A point to create, carrying its caller-minted id (decision 6: ids are
 * client-minted so verbs return identity synchronously).
 */
export interface PointSeed {
  id: PointId
  x: number
  y: number
  pointType: PointType
  smooth: boolean
}

export type PointType = "onCurve" | "offCurve";

export interface RemovePointsIntent {
  layerId: LayerId
  pointIds: Array<PointId>
}

export interface ReverseContourIntent {
  layerId: LayerId
  contourId: ContourId
}

export interface SetContourClosedIntent {
  layerId: LayerId
  contourId: ContourId
  closed: boolean
}

export interface SetPointSmoothIntent {
  layerId: LayerId
  pointId: PointId
  smooth: boolean
}

export interface SetXAdvanceIntent {
  layerId: LayerId
  width: number
}

export interface Source {
  id: SourceId
  name: string
  location: Location
  filename?: string
}

/** Affine move: O(selection-ids) wire instead of O(N) coords. */
export interface TranslatePointsIntent {
  layerId: LayerId
  pointIds: Array<PointId>
  dx: number
  dy: number
}
