import type {
  ContourId,
  PointId,
  AnchorId,
  AxisId,
  ComponentId,
  GuidelineId,
  GlyphId,
  LayerId,
  SourceId,
} from "../ids";

// This file is generated from crates/shift-bridge/index.d.ts.
// Run `pnpm generate:bridge-types` after rebuilding shift-bridge declarations.
// Do not edit this file manually.

export type GlyphName = string;
export type Unicode = number;

export interface BridgeApi {
  createUntitledWorkspace(storePath: string, options?: NewWorkspace | undefined | null): void
  exportWorkspace(request: FontExportRequest): Promise<FontExportResult>
  documentState(): DocumentState
  openWorkspace(path: string, storePath: string): void
  resumeWorkspaceForSource(storePath: string, sourcePath: string): void
  setDocumentId(documentId: string): DocumentState
  findRecoverableWorkspace(sourcePath: string, candidates: Array<WorkspaceRecoveryCandidate>): WorkspaceRecoveryMatch | null
  saveWorkspace(): DocumentState
  saveWorkspaceAs(path: string): DocumentState
  getMetadata(): FontMetadata
  getMetrics(): FontMetrics
  getGlyphs(): Array<GlyphRecord>
  /**
   * Applies one intent set as a single atomic workspace apply: every kind
   * — editing and create alike — decodes through `map_intent` into one
   * `FontWorkspace::apply` call. One call = one SQLite transaction = one
   * undo step, however many intents the set batches.
   */
  apply(intents: Array<FontIntent>, label?: string | undefined | null): AppliedChange
  /**
   * Replays the most recent ledger entry's pre states; `null` when the
   * undo stack is empty.
   */
  undo(): AppliedChange | null
  /**
   * Replays the most recent undone entry's post states; `null` when the
   * redo stack is empty.
   */
  redo(): AppliedChange | null
  /** Glyph-addressed snapshots for renderer-local synchronous font state. */
  getGlyphSnapshots(requests: Array<GlyphSnapshotRequest>): Array<GlyphSnapshot>
  isVariable(): boolean
  getAxes(): Array<Axis>
  getSources(): Array<Source>
}

export interface DocumentState {
  sourceKind: string
  saveTarget?: string
  dirty: boolean
  needsSaveAs: boolean
}

export interface FontExportRequest {
  path: string
  format: string
}

export interface FontExportResult {
  path: string
  format: string
}

export interface NewWorkspace {
  familyName?: string
  unitsPerEm?: number
}

export interface WorkspaceRecoveryCandidate {
  documentId: string
  storePath: string
}

export interface WorkspaceRecoveryMatch {
  documentId: string
  storePath: string
  matchKind: string
  dirty: boolean
}
export interface AddAnchorsIntent {
  layerId: LayerId
  anchors: Array<AnchorSeed>
}

export interface AddContourIntent {
  layerId: LayerId
  contourId: ContourId
  closed: boolean
}

export interface AddPointsIntent {
  layerId: LayerId
  /** Absent when `before` carries the anchor; Rust derives the contour. */
  contourId?: ContourId
  /** Insert before this point; append when absent. */
  before?: PointId
  points: Array<PointSeed>
}

export interface AnchorData {
  id: AnchorId
  name?: string
}

/**
 * An anchor to create, carrying its caller-minted id (decision 6: ids are
 * client-minted so verbs return identity synchronously).
 */
export interface AnchorSeed {
  id: AnchorId
  name?: string
  x: number
  y: number
}

/** Pure-state response to `apply`: no change records cross to the renderer. */
export interface AppliedChange {
  layers: Array<LayerReplaced>
  /** Full records list when glyph identity changed; absent when untouched. */
  glyphs?: Array<GlyphRecord>
  /** Full axes list when font-level axis structure changed; absent otherwise. */
  axes?: Array<Axis>
  /**
   * Full sources list when font-level source structure changed (createAxis
   * reshapes locations, createSource adds one); absent otherwise.
   */
  sources?: Array<Source>
  /** Stable ids: references survive renames without re-indexing. */
  dependents: Array<GlyphId>
}

export interface Axis {
  id: AxisId
  tag: string
  name: string
  minimum: number
  default: number
  maximum: number
  hidden: boolean
}

export interface AxisTent {
  axisTag: string
  lower: number
  peak: number
  upper: number
}

export interface BooleanOpIntent {
  layerId: LayerId
  contourIdA: ContourId
  contourIdB: ContourId
  /** "union" | "subtract" | "intersect" | "difference" */
  operation: string
}

export interface ComponentData {
  id: ComponentId
  baseGlyphId: GlyphId
  baseGlyphName: GlyphName
}

export interface ContourData {
  id: ContourId
  points: Array<PointData>
  closed: boolean
}

/**
 * Font-level axis creation. The axis id is client-minted; the tag is an
 * OpenType label and must be unique within the font.
 */
export interface CreateAxisIntent {
  axisId: AxisId
  tag: string
  name: string
  min: number
  default: number
  max: number
  hidden: boolean
}

/**
 * Font-level glyph creation. The glyph id is client-minted (decision 6:
 * verbs return identity synchronously); Rust honors it and rejects
 * duplicates.
 */
export interface CreateGlyphIntent {
  glyphId: GlyphId
  name: GlyphName
  unicodes: Array<Unicode>
}

/** Creates one sparse glyph layer at an existing source for an existing glyph. */
export interface CreateGlyphLayerIntent {
  layerId: LayerId
  glyphId: GlyphId
  sourceId: SourceId
}

/**
 * Font-level source creation. The source id is client-minted so verbs can
 * return identity synchronously; Rust honors it and rejects duplicates.
 */
export interface CreateSourceIntent {
  sourceId: SourceId
  name: string
  /** Axis id → design-space value for the new source. */
  location: Location
}

/** Font-level axis deletion. Removing an axis also reshapes source locations. */
export interface DeleteAxisIntent {
  axisId: AxisId
}

/** Font-level source deletion. Removing a source also removes its glyph layers. */
export interface DeleteSourceIntent {
  sourceId: SourceId
}

/**
 * CS0 walking-skeleton intent. A stringly union covering exactly the two
 * skeleton kinds; CS1 replaces this with per-variant intent structs.
 */
export interface FontIntent {
  /**
   * Discriminator naming the populated payload field. Editing kinds:
   * "addPoints" | "addContour" | "setContourClosed" | "movePoints" |
   * "setPointSmooth" | "removePoints" | "addAnchors" | "moveAnchors" |
   * "removeAnchors" | "reverseContour" | "translatePoints" |
   * "setXAdvance" | "applyBooleanOp".
   * Create kinds: "createGlyph" | "createAxis" | "createSource" |
   * "createGlyphLayer". Delete kinds: "deleteAxis" | "deleteSource". Every
   * kind shares the same apply path; one set = one undo step.
   */
  kind: string
  addPoints?: AddPointsIntent
  addContour?: AddContourIntent
  setContourClosed?: SetContourClosedIntent
  movePoints?: MovePointsIntent
  setPointSmooth?: SetPointSmoothIntent
  removePoints?: RemovePointsIntent
  addAnchors?: AddAnchorsIntent
  moveAnchors?: MoveAnchorsIntent
  removeAnchors?: RemoveAnchorsIntent
  reverseContour?: ReverseContourIntent
  translatePoints?: TranslatePointsIntent
  setXAdvance?: SetXAdvanceIntent
  applyBooleanOp?: BooleanOpIntent
  createGlyph?: CreateGlyphIntent
  updateGlyph?: UpdateGlyphIntent
  createAxis?: CreateAxisIntent
  deleteAxis?: DeleteAxisIntent
  createSource?: CreateSourceIntent
  deleteSource?: DeleteSourceIntent
  createGlyphLayer?: CreateGlyphLayerIntent
}

export interface FontMetadata {
  familyName?: string
  styleName?: string
  versionMajor?: number
  versionMinor?: number
  copyright?: string
  trademark?: string
  designer?: string
  designerUrl?: string
  manufacturer?: string
  manufacturerUrl?: string
  license?: string
  licenseUrl?: string
  description?: string
  note?: string
}

export interface FontMetrics {
  unitsPerEm: number
  ascender: number
  descender: number
  capHeight?: number
  xHeight?: number
  lineGap?: number
  italicAngle?: number
  underlinePosition?: number
  underlineThickness?: number
}

export interface GlyphChangedEntities {
  pointIds: Array<PointId>
  contourIds: Array<ContourId>
  anchorIds: Array<AnchorId>
  guidelineIds: Array<GuidelineId>
  componentIds: Array<ComponentId>
}

export interface GlyphLayerRecord {
  id: LayerId
  sourceId: SourceId
}

export interface GlyphLayerSnapshot {
  glyphId: GlyphId
  sourceId: SourceId
  state: GlyphState
}

export interface GlyphMaster {
  sourceId: SourceId
  sourceName: string
  isDefaultSource: boolean
  location: Location
  structure: GlyphStructure
  values: Float64Array
}

export interface GlyphRecord {
  id: GlyphId
  name: GlyphName
  unicodes: Array<Unicode>
  componentBaseGlyphIds: Array<GlyphId>
  layers: Array<GlyphLayerRecord>
}

export interface GlyphSnapshot {
  glyphId: GlyphId
  variationData?: GlyphVariationData
  layers: Array<GlyphLayerSnapshot>
}

export interface GlyphSnapshotRequest {
  glyphId: GlyphId
  sourceIds: SourceId[]
}

export interface GlyphState {
  layerId: LayerId
  structure: GlyphStructure
  /** Numeric glyph state ordered to match `GlyphStructure`. */
  values: Float64Array
}

export interface GlyphStructure {
  contours: Array<ContourData>
  anchors: Array<AnchorData>
  components: Array<ComponentData>
}

export interface GlyphVariationData {
  /** One entry per region. Inner = tents on the axes the region depends on. */
  regions: Array<Array<AxisTent>>
  /** Deltas are flattened in `GlyphState::values` order. */
  deltas: Array<Float64Array>
}

/**
 * Replace-grade state for one touched layer; the renderer folds by
 * substitution, never by interpreting changes.
 */
export interface LayerReplaced {
  layerId: LayerId
  /** Present only when the layer's structure changed. */
  structure?: GlyphStructure
  values: Float64Array
  changed: GlyphChangedEntities
}

export interface Location {
  values: Record<AxisId, number>
}

export interface MoveAnchorsIntent {
  layerId: LayerId
  anchorIds: Array<AnchorId>
  /** Interleaved absolute coordinates: x0, y0, x1, y1, … */
  coords: Array<number>
}

export interface MovePointsIntent {
  layerId: LayerId
  pointIds: Array<PointId>
  /** Interleaved absolute coordinates: x0, y0, x1, y1, … */
  coords: Array<number>
}

export interface PointData {
  id: PointId
  pointType: PointType
  smooth: boolean
}

/**
 * A point to create, carrying its caller-minted id (decision 6: ids are
 * client-minted so verbs return identity synchronously).
 */
export interface PointSeed {
  id: PointId
  x: number
  y: number
  pointType: PointType
  smooth: boolean
}

export type PointType = "onCurve" | "offCurve";

export interface RemoveAnchorsIntent {
  layerId: LayerId
  anchorIds: Array<AnchorId>
}

export interface RemovePointsIntent {
  layerId: LayerId
  pointIds: Array<PointId>
}

export interface ReverseContourIntent {
  layerId: LayerId
  contourId: ContourId
}

export interface SetContourClosedIntent {
  layerId: LayerId
  contourId: ContourId
  closed: boolean
}

export interface SetPointSmoothIntent {
  layerId: LayerId
  pointId: PointId
  smooth: boolean
}

export interface SetXAdvanceIntent {
  layerId: LayerId
  width: number
}

export interface Source {
  id: SourceId
  name: string
  location: Location
  filename?: string
}

/** Affine move: O(selection-ids) wire instead of O(N) coords. */
export interface TranslatePointsIntent {
  layerId: LayerId
  pointIds: Array<PointId>
  dx: number
  dy: number
}

/**
 * Font-level glyph update. The glyph id targets an existing committed glyph;
 * names are user-editable labels and are not stable identity.
 */
export interface UpdateGlyphIntent {
  glyphId: GlyphId
  newName: GlyphName
  newUnicodes: Array<Unicode>
}
