import type { GlyphName, Unicode } from "./generated";

export type {
  AddAnchorsIntent,
  AddContourIntent,
  AddPointsIntent,
  AnchorData,
  AnchorSeed,
  AppliedChange,
  BooleanOpIntent,
  MoveAnchorsIntent,
  MovePointsIntent,
  RemoveAnchorsIntent,
  RemovePointsIntent,
  ReverseContourIntent,
  SetContourClosedIntent,
  SetPointSmoothIntent,
  SetXAdvanceIntent,
  TranslatePointsIntent,
  Axis,
  AxisLabel,
  AxisMapping,
  AxisMappingPoint,
  AxisRole,
  AxisType,
  BridgeApi,
  ComponentData,
  ContourData,
  CreateAxisIntent,
  CreateGlyphLayerIntent,
  CreateNamedInstanceIntent,
  DeleteAxisIntent,
  DeleteNamedInstanceIntent,
  DeleteSourceIntent,
  CreateSourceIntent,
  FontIntent,
  FontMetadata,
  FontMetrics,
  GlyphChangedEntities,
  GlyphLayerRecord,
  GlyphName,
  GlyphInterpolation,
  GlyphProjection,
  GlyphRecord,
  GlyphShape,
  GlyphSourceShape,
  GlyphSourceValues,
  GlyphState,
  GlyphStructure,
  InterpolationBasis,
  InterpolationSupport,
  LayerReplaced,
  Location,
  NamedInstance,
  PackageDraft,
  PackageIdentity,
  PointData,
  PointSeed,
  PointType,
  SetAxisMappingsIntent,
  Source,
  Unicode,
  UpdateAxisIntent,
  UpdateFontMetadataIntent,
  UpdateNamedInstanceIntent,
} from "./generated";

/**
 * Renderer-side glyph address: a name plus optional unicode. This no longer
 * crosses the NAPI boundary (id-addressed `getGlyph` replaced the
 * handle-addressed read), but the renderer still uses it to identify glyphs.
 */
export interface GlyphHandle {
  name: GlyphName;
  unicode?: Unicode;
}
