import type { GlyphName, Unicode } from "./generated";

export type {
  AddAnchorsIntent,
  AddContourIntent,
  AddPointsIntent,
  AnchorData,
  AnchorSeed,
  AppliedChange,
  BooleanOpIntent,
  MoveAnchorsIntent,
  MovePointsIntent,
  RemoveAnchorsIntent,
  RemovePointsIntent,
  ReverseContourIntent,
  SetContourClosedIntent,
  SetPointSmoothIntent,
  SetXAdvanceIntent,
  SlugAtlas,
  SlugExactSource,
  SlugGlyph,
  SlugLayout,
  SlugPreviewExtents,
  SlugSection,
  SlugWeightSet,
  TranslatePointsIntent,
  Axis,
  AxisLabel,
  AxisMapping,
  AxisMappingBasis,
  AxisMappingPoint,
  AxisRole,
  AxisType,
  BridgeApi,
  CatalogAtlasGlyph,
  CatalogAtlasPage,
  CatalogAtlasWeights,
  CatalogAxis,
  CatalogMetrics,
  ComponentAnchorAttachment,
  ComponentAnchorReference,
  ComponentData,
  ComponentGlyph,
  ComponentTransformKind,
  ContourData,
  CreateAxisIntent,
  CreateGlyphLayerIntent,
  CreateNamedInstanceIntent,
  DeleteAxisIntent,
  DeleteNamedInstanceIntent,
  DeleteSourceIntent,
  CreateSourceIntent,
  DocumentIdentity,
  FontIntent,
  FontMetadata,
  FontSnapshot,
  FontMetrics,
  MetricDefinition,
  MetricKind,
  SourceMetricField,
  SourceMetricsInterpolationReplacement,
  SourceMetricsInterpolationSnapshot,
  GlyphChangedEntities,
  GlyphComponents,
  GlyphEntry,
  GlyphLayerRecord,
  GlyphLayerShape,
  GlyphName,
  GlyphInterpolation,
  GlyphPreview,
  GlyphProjection,
  GlyphRecord,
  GlyphSourceComponents,
  GlyphSourceShape,
  GlyphSourceValues,
  GlyphSnapshot,
  GlyphSnapshotRequest,
  GlyphState,
  GlyphStructure,
  GlyphVariation,
  InterpolationBasis,
  InterpolationSupport,
  LayerReplaced,
  Location,
  NamedInstance,
  PointData,
  PointSeed,
  PointType,
  SetAxisMappingsIntent,
  SetMetricDefinitionsIntent,
  Source,
  SourceMetricValue,
  Unicode,
  UpdateAxisIntent,
  UpdateFontMetadataIntent,
  UpdateNamedInstanceIntent,
  UpdateSourceIntent,
  VariationBasis,
  VariationDelta,
} from "./generated";

/**
 * Renderer-side glyph address: a name plus optional unicode. This no longer
 * crosses the NAPI boundary (id-addressed `getGlyph` replaced the
 * handle-addressed read), but the renderer still uses it to identify glyphs.
 */
export interface GlyphHandle {
  name: GlyphName;
  unicode?: Unicode;
}
