// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IContourPoint } from "./IContourPoint";

export type Contour = { points: Array<IContourPoint>, closed: boolean, };
