// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointType } from "./PointType";

export type ContourPoint = { pointType: PointType, x: number, y: number, smooth: boolean, };
