// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContourPoint } from "./ContourPoint";

export type Contour = { points: Array<ContourPoint>, closed: boolean, };
