// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontMetadata } from "./FontMetadata";
import type { Glyph } from "./Glyph";
import type { Metrics } from "./Metrics";

export type Font = { metadata: FontMetadata, metrics: Metrics, glyphs: { [key in number]?: Glyph }, };
