// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IContour } from "./IContour";

export type Glyph = { name: string, unicode: number, contours: Array<IContour>, x_advance: number, };
