// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Contour } from "./Contour";

export type Glyph = { name: string, unicode: string, contours: Array<Contour>, x_advance: number, };
