// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";

export type MovedPoint = { pointId: EntityId, fromX: number, fromY: number, toX: number, toY: number, };
