// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathCommand = { "type": "moveTo", x: number, y: number, } | { "type": "lineTo", x: number, y: number, } | { "type": "cubicTo", cp1x: number, cp1y: number, cp2x: number, cp2y: number, x: number, y: number, } | { "type": "quadTo", cp1x: number, cp1y: number, x: number, y: number, } | { "type": "close" };
