[project]
name = "unicode"
version = "0.1.0"
description = "Generate unicode tables for Rust"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fonttools>=4.56.0",
    "requests>=2.32.3",
]
