#!/usr/bin/env npx tsx

/**
 * Post-processes ts-rs generated TypeScript files to add imports for branded ID types.
 *
 * ts-rs doesn't support importing external types when using #[ts(type = "...")],
 * so we patch the generated files to add the necessary imports.
 *
 * Run this after `cargo test --package shift-core` to ensure types are complete.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const GENERATED_DIR = path.join(__dirname, "../packages/types/src/generated");

const FILE_IMPORTS: Record<string, string[]> = {
  "PointSnapshot.ts": ["PointId"],
  "ContourSnapshot.ts": ["ContourId"],
  "GlyphSnapshot.ts": ["ContourId"],
  "CommandResult.ts": ["PointId"],
};

function patchFile(filename: string, imports: string[]): boolean {
  const filePath = path.join(GENERATED_DIR, filename);

  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  File not found: ${filename}`);
    return false;
  }

  let content = fs.readFileSync(filePath, "utf8");

  const importStatement = `import type { ${imports.join(", ")} } from "../ids";\n`;

  if (content.includes('from "../ids"')) {
    console.log(`✓  ${filename} already patched`);
    return true;
  }

  const tsrsComment =
    "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

  if (content.startsWith(tsrsComment)) {
    content = tsrsComment + "\n" + importStatement + content.slice(tsrsComment.length);
  } else {
    content = importStatement + content;
  }

  fs.writeFileSync(filePath, content);
  console.log(`✅ Patched ${filename} with imports: ${imports.join(", ")}`);
  return true;
}

function main(): void {
  console.log("🔧 Patching generated types with branded ID imports...\n");

  let success = true;

  for (const [filename, imports] of Object.entries(FILE_IMPORTS)) {
    if (!patchFile(filename, imports)) {
      success = false;
    }
  }

  console.log("");

  if (success) {
    console.log("✅ All generated types patched successfully!");
  } else {
    console.error("❌ Some files could not be patched");
    process.exit(1);
  }
}

main();
