#!/usr/bin/env npx tsx

/**
 * Post-processes ts-rs generated TypeScript files to add imports for branded ID types.
 *
 * ts-rs doesn't support importing external types when using #[ts(type = "...")],
 * so we patch the generated files to add the necessary imports.
 *
 * Run this after `cargo test --package shift-core` to ensure types are complete.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const GENERATED_DIR = path.join(__dirname, "../packages/types/src/generated");

const FILE_IMPORTS: Record<string, string[]> = {
  "AnchorSnapshot.ts": ["AnchorId"],
  "PointSnapshot.ts": ["PointId"],
  "ContourSnapshot.ts": ["ContourId"],
  "GlyphSnapshot.ts": ["ContourId"],
  "CommandResult.ts": ["PointId"],
};

/** Match what pre-commit's trailing-whitespace + end-of-file-fixer do, so the
 *  hooks don't re-modify these files on every commit attempt. ts-rs emits
 *  trailing whitespace and no terminating newline. */
function normalizeWhitespace(content: string): string {
  return (
    content
      .split("\n")
      .map((line) => line.replace(/[ \t]+$/, ""))
      .join("\n")
      .replace(/\n*$/, "") + "\n"
  );
}

function patchFile(filename: string, imports: string[]): boolean {
  const filePath = path.join(GENERATED_DIR, filename);

  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  File not found: ${filename}`);
    return false;
  }

  let content = fs.readFileSync(filePath, "utf8");

  const importStatement = `import type { ${imports.join(", ")} } from "../ids";\n`;
  const tsrsComment =
    "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

  const alreadyHasImport = content.includes('from "../ids"');

  if (!alreadyHasImport) {
    if (content.startsWith(tsrsComment)) {
      content = tsrsComment + "\n" + importStatement + content.slice(tsrsComment.length);
    } else {
      content = importStatement + content;
    }
  }

  content = normalizeWhitespace(content);

  // Avoid touching disk if nothing actually changed — keeps git unaware.
  const existing = fs.readFileSync(filePath, "utf8");
  if (existing === content) {
    console.info(`✓  ${filename} already patched`);
    return true;
  }

  fs.writeFileSync(filePath, content);
  console.info(`✅ Patched ${filename} with imports: ${imports.join(", ")}`);
  return true;
}

function patchNapiDts(): boolean {
  const napiDtsPath = path.join(__dirname, "../crates/shift-node/index.d.ts");

  if (!fs.existsSync(napiDtsPath)) {
    console.warn("⚠️  shift-node/index.d.ts not found — run `pnpm build:native` first");
    return true;
  }

  let content = fs.readFileSync(napiDtsPath, "utf8");
  const importLine = 'import type { ContourId, PointId, AnchorId } from "@shift/types";';

  if (content.includes(importLine)) {
    console.info("✓  shift-node/index.d.ts already patched");
    return true;
  }

  const marker = "/* auto-generated by NAPI-RS */";
  if (content.includes(marker)) {
    content = content.replace(marker, marker + "\n\n" + importLine);
  } else {
    content = importLine + "\n\n" + content;
  }

  fs.writeFileSync(napiDtsPath, content);
  console.info("✅ Patched shift-node/index.d.ts with branded ID imports");
  return true;
}

/** Normalize whitespace on every generated file (whether it needs an ID
 *  import or not). ts-rs emits trailing whitespace + no terminating newline
 *  — left untouched, pre-commit's trailing-whitespace + end-of-file-fixer
 *  hooks would re-flag every commit. */
function normalizeAllGenerated(): void {
  if (!fs.existsSync(GENERATED_DIR)) return;
  for (const filename of fs.readdirSync(GENERATED_DIR)) {
    if (!filename.endsWith(".ts")) continue;
    if (filename in FILE_IMPORTS) continue; // patchFile already normalised
    const filePath = path.join(GENERATED_DIR, filename);
    const original = fs.readFileSync(filePath, "utf8");
    const normalized = normalizeWhitespace(original);
    if (original !== normalized) {
      fs.writeFileSync(filePath, normalized);
      console.info(`✅ Normalised whitespace in ${filename}`);
    }
  }
}

function main(): void {
  console.info("🔧 Patching generated types with branded ID imports...\n");

  let success = true;

  for (const [filename, imports] of Object.entries(FILE_IMPORTS)) {
    if (!patchFile(filename, imports)) {
      success = false;
    }
  }

  normalizeAllGenerated();

  if (!patchNapiDts()) {
    success = false;
  }

  console.info("");

  if (success) {
    console.info("✅ All generated types patched successfully!");
  } else {
    console.error("❌ Some files could not be patched");
    process.exit(1);
  }
}

main();
