/**
 * Variable-font interpolation — per-tick eval path.
 *
 * The hard math (region construction + delta decomposition) lives in Rust via
 * `fontdrasil`. This module is the trivial per-tick eval — region tent function
 * and a dot product against cached deltas. Ported faithfully from fontdrasil's
 * `scalar_at_with_args` and `interpolate_from_deltas`.
 *
 * Parity-tested against `packages/types/__fixtures__/variation_parity.json`,
 * generated by `crates/shift-core/tests/interpolation_parity.rs`.
 */

import type { Axis, AxisLocation, AxisTent, GlyphVariationData } from "@shift/types";

export type NormalizedLocation = Record<string, number>;

/** Asymmetric normalize — mirrors `Axis::normalize` in shift-ir/src/axis.rs. */
export function normalizeAxis(value: number, axis: Axis): number {
  if (value < axis.default) {
    const range = axis.default - axis.minimum;
    return range === 0 ? 0 : (value - axis.default) / range;
  }
  if (value > axis.default) {
    const range = axis.maximum - axis.default;
    return range === 0 ? 0 : (value - axis.default) / range;
  }
  return 0;
}

export function normalize(loc: AxisLocation, axes: Axis[]): NormalizedLocation {
  const out: NormalizedLocation = {};
  for (const axis of axes) {
    out[axis.tag] = normalizeAxis(loc[axis.tag] ?? axis.default, axis);
  }
  return out;
}

/** Mirrors fontdrasil's `Tent::validate` — used as a per-tent filter. */
function isValidTent(t: AxisTent): boolean {
  if (t.lower > t.peak || t.peak > t.upper) return false;
  if (t.lower < 0 && t.upper > 0) return false; // can't span across default
  return true;
}

/**
 * Scalar contribution of a region at a normalized location.
 * Exact port of fontdrasil's `VariationRegion::scalar_at_with_args` (no extrapolation).
 */
export function scalarAt(loc: NormalizedLocation, region: AxisTent[]): number {
  let scalar = 1;
  for (const t of region) {
    if (!isValidTent(t)) continue;

    const v = loc[t.axisTag] ?? 0;

    if (v === t.peak) continue;

    if (t.lower === 0 && t.peak === 0 && t.upper === 0) {
      continue; // (0,0,0) tent = always-on (default region)
    }

    if (v <= t.lower || t.upper <= v) return 0; // outside, boundary inclusive

    const edge = v < t.peak ? t.lower : t.upper;
    scalar *= (v - edge) / (t.peak - edge);
  }
  return scalar;
}

/**
 * Evaluate per-region deltas at a normalized location.
 * Exact port of fontdrasil's `VariationModel::interpolate_from_deltas` (no extrapolation).
 *
 * Output values are absolute (not offsets from default) because the default
 * master's region has empty/zero support and contributes its full delta at scalar=1.
 *
 * Order is the `flatten()` shape from shift-core::interpolation:
 *   [xAdvance, p0.x, p0.y, p1.x, p1.y, ..., a0.x, a0.y, ...]
 */
export function interpolate(data: GlyphVariationData, loc: NormalizedLocation): Float64Array {
  const len = data.deltas[0]?.length ?? 0;
  const result = new Float64Array(len);
  for (let r = 0; r < data.regions.length; r++) {
    const s = scalarAt(loc, data.regions[r]);
    if (s === 0) continue;
    const d = data.deltas[r];
    for (let i = 0; i < len; i++) result[i] += s * d[i];
  }
  return result;
}
