import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { GlyphVariationData } from "@shift/types";
import { interpolate, scalarAt, type NormalizedLocation } from "./interpolate";

interface MasterEntry {
  sourceName: string;
  isDefaultSource: boolean;
  designspaceLocation: Record<string, number>;
  normalisedLocation: NormalizedLocation;
  expected: number[];
}

interface Fixture {
  glyphName: string;
  designspaceTarget: Record<string, number>;
  normalisedLocation: NormalizedLocation;
  data: GlyphVariationData;
  expected: number[];
  masters: MasterEntry[];
}

function loadFixture(): Fixture {
  // Generated by `cargo test -p shift-core --test interpolation_parity`.
  // vitest runs with cwd at apps/desktop; repo root is two up.
  const path = resolve(process.cwd(), "../../packages/types/__fixtures__/variation_parity.json");
  return JSON.parse(readFileSync(path, "utf-8")) as Fixture;
}

describe("interpolate — parity with fontdrasil", () => {
  it("matches Rust interpolate_from_deltas at the fixture target", () => {
    const fx = loadFixture();
    const result = interpolate(fx.data, fx.normalisedLocation);

    expect(result.length).toBe(fx.expected.length);
    const tolerance = 1e-9;
    for (let i = 0; i < result.length; i++) {
      const diff = Math.abs(result[i] - fx.expected[i]);
      expect(
        diff,
        `index ${i}: got ${result[i]}, expected ${fx.expected[i]}, diff ${diff}`,
      ).toBeLessThan(tolerance);
    }
  });

  it("returns the default master values at the origin", () => {
    const fx = loadFixture();
    const origin: NormalizedLocation = {};
    for (const tag of Object.keys(fx.normalisedLocation)) origin[tag] = 0;

    const result = interpolate(fx.data, origin);
    // Default master = first deltas entry (its region has all-zero tents → scalar 1
    // at origin and elsewhere; other regions have non-zero scalar only off-origin).
    // At origin, only the default's contribution should remain.
    expect(result.length).toBe(fx.data.deltas[0].length);
    for (let i = 0; i < result.length; i++) {
      expect(Math.abs(result[i] - fx.data.deltas[0][i])).toBeLessThan(1e-9);
    }
  });
});

describe("interpolate — round-trip at master locations", () => {
  // Strongest defence against unpacking drift: at each master's location, the
  // interpolated values must match that master's stored flat geometry. This
  // exercises every region's tent in turn (each master sits at exactly one
  // off-default region's peak, plus the default region with scalar=1).
  it("recovers each master's flat values when interpolating at its own location", () => {
    const fx = loadFixture();
    expect(fx.masters.length).toBeGreaterThan(0);

    for (const master of fx.masters) {
      const result = interpolate(fx.data, master.normalisedLocation);

      expect(result.length, `${master.sourceName}: length`).toBe(master.expected.length);
      for (let i = 0; i < result.length; i++) {
        const diff = Math.abs(result[i] - master.expected[i]);
        expect(
          diff,
          `${master.sourceName} index ${i}: got ${result[i]}, expected ${master.expected[i]}, diff ${diff}`,
        ).toBeLessThan(1e-9);
      }
    }
  });

  it("identifies exactly one default master in the fixture", () => {
    // Sanity check on the fixture itself — fontdrasil's invariant.
    const fx = loadFixture();
    const defaults = fx.masters.filter((m) => m.isDefaultSource);
    expect(defaults.length).toBe(1);
  });
});

describe("scalarAt — boundary semantics", () => {
  it("returns 1 at the peak", () => {
    expect(scalarAt({ wght: 0.5 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }])).toBe(1);
  });

  it("returns 0 at the lower boundary (inclusive)", () => {
    expect(scalarAt({ wght: 0 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }])).toBe(0);
  });

  it("returns 0 at the upper boundary (inclusive)", () => {
    expect(scalarAt({ wght: 1 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }])).toBe(0);
  });

  it("returns 0 outside the tent", () => {
    expect(scalarAt({ wght: 1.5 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }])).toBe(0);
    expect(scalarAt({ wght: -0.5 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }])).toBe(0);
  });

  it("ramps linearly from lower to peak", () => {
    // halfway between lower=0 and peak=0.5 → scalar 0.5
    expect(
      scalarAt({ wght: 0.25 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }]),
    ).toBeCloseTo(0.5, 9);
  });

  it("ramps linearly from peak to upper", () => {
    // halfway between peak=0.5 and upper=1 → scalar 0.5
    expect(
      scalarAt({ wght: 0.75 }, [{ axisTag: "wght", lower: 0, peak: 0.5, upper: 1 }]),
    ).toBeCloseTo(0.5, 9);
  });

  it("treats (0,0,0) tent as always-on", () => {
    // Default-region tents — full influence regardless of location
    expect(scalarAt({ wght: 0.7 }, [{ axisTag: "wght", lower: 0, peak: 0, upper: 0 }])).toBe(1);
  });

  it("multiplies scalars across multiple axes", () => {
    // Each axis halfway up its ramp → 0.5 × 0.5 = 0.25
    const region = [
      { axisTag: "wght", lower: 0, peak: 0.5, upper: 1 },
      { axisTag: "wdth", lower: 0, peak: 0.5, upper: 1 },
    ];
    expect(scalarAt({ wght: 0.25, wdth: 0.25 }, region)).toBeCloseTo(0.25, 9);
  });

  it("returns 0 for invalid tents (peak < lower)", () => {
    expect(scalarAt({ wght: 0.5 }, [{ axisTag: "wght", lower: 0.5, peak: 0, upper: 1 }])).toBe(1); // invalid tent skipped, no other tents → scalar stays 1
  });
});
